run:
    timeout: 5m

linters-settings:
    gci:
        sections:
            - standard
            - default
            - prefix(github.com/spf13/viper)
    gocritic:
        # Enable multiple checks by tags. See "Tags" section in https://github.com/go-critic/go-critic#usage.
        enabled-tags:
            - diagnostic
            - experimental
            - opinionated
            - style
        disabled-checks:
            - importShadow
            - unnamedResult
    golint:
        min-confidence: 0
    goimports:
        local-prefixes: github.com/spf13/viper

linters:
    enable-all: true
    disable:
      - depguard
